# Generated by Django 3.2.2 on 2022-10-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_projectimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectImages',
            new_name='ProjectImage',
        ),
    ]
